### ISSUE TITLE
4.4.0-1.1 make: unknown option -- no-print-directory

### ISSUE THREAD

**Issue by urusov-a59** [xpack/web-jekyll#18]
4.4.0-1.1
Project has Post-build step.
generated make has lines:
  _**78 # All Target
  79  all:
  80 	+@$(MAKE) --no-print-directory main-build && $(MAKE) --no-print-directory post-build**_
Output:
  **_make all 
  make: unknown option -- no-print-directory
  BusyBox v1.36.0.git (2023-01-29 16:36:13 UTC)
  ...........
 make: *** [makefile:80: all] Error 1_**

V.4.3.0-1.1 works normal

**Comment by ilg-ul** [comment]
Can you provide more details? Where does `make` come into play? I don't remember using it.

**Comment by urusov-a59** [comment]
Hi
I use Eclipse Eclipse IDE for Embedded C/C++ Developers (includes Incubating components)
Version: 2023-09 (4.29.0)
Build id: 20230907-1323
OS: Windows 10, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.8.1+1
Java version: 17.0.8.1

RISC-V GNU Toolchain - xpack-dev-tools/riscv-none-embed-gcc/10.2.0-1.2.1

I think, that  auto generated makefile not compatible with make tool.

**Comment by ilg-ul** [comment]
If the issue is related to the make tool, why did you enter it in the project related to the content of the web site?

**Comment by urusov-a59** [comment]
Easy way for me,  use V.4.3.0-1.1 of windows tools, where make tool understand option --no-print-directory.
Best regards.

**Comment by urusov-a59** [comment]
I just wanted to draw your attention to this
